// <auto-generated />
namespace Bookstore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class itemcost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemcost));
        
        string IMigrationMetadata.Id
        {
            get { return "201903112039077_itemcost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
